### ISSUE TITLE
Inkcut

### ISSUE THREAD

**Issue by kuhlone** [inkcut/inkcut#151]
I am getting the following error after adding the Inkcut files to the Inkscape extensions folder.  Thoughts?
Traceback (most recent call last):
  File "inkcut_cut.py", line 73, in <module>
    effect.affect()
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex.py", line 268, in affect
    self.effect()
  File "inkcut_cut.py", line 67, in effect
    close_fds=sys.platform != "win32")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by frmdstryr** [comment]
Looks like the extension was installed but not Inkcut itself.

See https://www.codelv.com/projects/inkcut/docs/installing
