### ISSUE TITLE
Inkcut crashes when selecting Vinylmark R2Rv1

### ISSUE THREAD

**Issue by vmario89** [inkcut/inkcut#207]
hi,
i figured out that Inkcut 2.1.1 always crashed when selecting this device
![grafik](https://user-images.githubusercontent.com/5631071/72692649-64dd1900-3b2d-11ea-9a2a-c3d2b20cd284.png)

the log output is
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Lib\site-packages\enaml\qt\qt_object_combo.py", line 117, in on_index_changed
  File "Lib\site-packages\enaml\core\declarative_meta.py", line 68, in declarative_change_handler
  File "Lib\site-packages\enaml\core\expression_engine.py", line 217, in write
  File "Lib\site-packages\enaml\core\standard_handlers.py", line 82, in __call__
  File "C:\Users\mario\AppData\Local\Programs\Python\Python37\Lib\site-packages\inkcut\dist\inkcut\inkcut\device\dialogs.enaml", line 65, in f
    dialog.device = plugin.get_device_from_driver(change['value'])
  File "Lib\site-packages\enaml\core\standard_tracer.py", line 60, in __call__
  File "Lib\site-packages\enaml\core\expression_engine.py", line 248, in update
  File "Lib\site-packages\enaml\core\standard_handlers.py", line 101, in __call__
  File "C:\Users\mario\AppData\Local\Programs\Python\Python37\Lib\site-packages\inkcut\dist\inkcut\inkcut\device\dialogs.enaml", line 99, in <module>
    } if device else {Model:ConfigView}
  File "C:\Users\mario\AppData\Local\Programs\Python\Python37\Lib\site-packages\inkcut\dist\inkcut\inkcut\device\pi\manifest.enaml", line 29, in config_view_factory
    from .view import ConfigView
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "Lib\site-packages\enaml\core\import_hooks.py", line 208, in exec_module
  File "Lib\site-packages\enaml\core\import_hooks.py", line 469, in get_code
  File "Lib\site-packages\enaml\core\import_hooks.py", line 433, in compile_code
  File "Lib\site-packages\enaml\core\parser\__init__.py", line 48, in parse
  File "Lib\site-packages\enaml\core\parser\base_parser.py", line 201, in parse
  File "C:\Users\mario\AppData\Local\Programs\Python\Python37\Lib\site-packages\inkcut\dist\inkcut\inkcut\device\pi\view.enaml", line 72
    tr("pi", text = "Scale")
    ^
SyntaxError: invalid syntax
```
all other devices seem to work in selection dropbox

**Comment by frmdstryr** [comment]
Thanks that code was leftover from a little project and seems it was broken when translation was added.
Fixed in https://github.com/inkcut/inkcut/commit/86255579a82c8cdeb84ac56e534a0c99aee09bc2
