### ISSUE TITLE
NotImplementedError in ZMQStream with pyqtgraph-0.11.0rc0

### ISSUE THREAD

**Issue by ratsputin** [inkcut/inkcut#249]
On a new install using python 3.8.3 on Windows, initially had the issue:
`AttributeError: module 'time' has no attribute 'clock'`
Upgrade pyqtgraph to 0.11rc0 based on another ticket which resolved this issue.

Now, seeing the following:
```
2020-05-25 14:15:23,191 | ERROR   | inkcut | Traceback (most recent call last):
  File "c:\program files (x86)\python38-32\lib\site-packages\traitlets\traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'iopub_socket'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files (x86)\python38-32\lib\site-packages\traitlets\traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'iopub_thread'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files (x86)\python38-32\lib\site-packages\inkcut\core\plugin.py", line 66, in start_default_workspace
    ui.select_workspace('inkcut.workspace')
  File "c:\program files (x86)\python38-32\lib\site-packages\enaml\workbench\ui\ui_plugin.py", line 158, in select_workspace
    self._model.workspace = new_workspace
  File "c:\program files (x86)\python38-32\lib\site-packages\enaml\core\standard_tracer.py", line 55, in __call__
    engine.update(owner, self.name)
  File "c:\program files (x86)\python38-32\lib\site-packages\enaml\core\expression_engine.py", line 241, in update
    setattr(owner, name, pair.reader(owner, name))
  File "c:\program files (x86)\python38-32\lib\site-packages\enaml\core\include.py", line 85, in _observe_objects
    self.parent.insert_children(self, newvalue)
  File "c:\program files (x86)\python38-32\lib\site-packages\enaml\core\object.py", line 228, in insert_children
    child_added(child)
  File "c:\program files (x86)\python38-32\lib\site-packages\enaml\widgets\toolkit_object.py", line 185, in child_added
    child.activate_proxy()
  File "c:\program files (x86)\python38-32\lib\site-packages\enaml\widgets\toolkit_object.py", line 213, in activate_proxy
    child.activate_proxy()
  File "c:\program files (x86)\python38-32\lib\site-packages\enaml\widgets\toolkit_object.py", line 213, in activate_proxy
    child.activate_proxy()
  File "c:\program files (x86)\python38-32\lib\site-packages\enaml\widgets\toolkit_object.py", line 213, in activate_proxy
    child.activate_proxy()
  [Previous line repeated 1 more time]
  File "c:\program files (x86)\python38-32\lib\site-packages\enaml\widgets\toolkit_object.py", line 210, in activate_proxy
    self.activate_top_down()
  File "c:\program files (x86)\python38-32\lib\site-packages\enaml\widgets\toolkit_object.py", line 226, in activate_top_down
    self.proxy.activate_top_down()
  File "c:\program files (x86)\python38-32\lib\site-packages\enaml\qt\qt_toolkit_object.py", line 76, in activate_top_down
    self.init_widget()
  File "c:\program files (x86)\python38-32\lib\site-packages\enaml\qt\qt_ipython_console.py", line 62, in init_widget
    self._setup_kernel()
  File "c:\program files (x86)\python38-32\lib\site-packages\enaml\qt\qt_ipython_console.py", line 96, in _setup_kernel
    kernel_manager.start_kernel(show_banner=False)
  File "c:\program files (x86)\python38-32\lib\site-packages\ipykernel\inprocess\manager.py", line 46, in start_kernel
    self.kernel = InProcessKernel(parent=self, session=self.session)
  File "c:\program files (x86)\python38-32\lib\site-packages\ipykernel\inprocess\ipkernel.py", line 72, in __init__
    super(InProcessKernel, self).__init__(**traits)
  File "c:\program files (x86)\python38-32\lib\site-packages\ipykernel\ipkernel.py", line 71, in __init__
    self.shell.displayhook.pub_socket = self.iopub_socket
  File "c:\program files (x86)\python38-32\lib\site-packages\traitlets\traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "c:\program files (x86)\python38-32\lib\site-packages\traitlets\traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "c:\program files (x86)\python38-32\lib\site-packages\ipykernel\inprocess\ipkernel.py", line 67, in _default_iopub_socket
    return self.iopub_thread.background_socket
  File "c:\program files (x86)\python38-32\lib\site-packages\traitlets\traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "c:\program files (x86)\python38-32\lib\site-packages\traitlets\traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "c:\program files (x86)\python38-32\lib\site-packages\ipykernel\inprocess\ipkernel.py", line 59, in _default_iopub_thread
    thread = IOPubThread(self._underlying_iopub_socket)
  File "c:\program files (x86)\python38-32\lib\site-packages\ipykernel\iostream.py", line 71, in __init__
    self._setup_event_pipe()
  File "c:\program files (x86)\python38-32\lib\site-packages\ipykernel\iostream.py", line 90, in _setup_event_pipe
    self._event_puller = ZMQStream(pipe_in, self.io_loop)
  File "c:\program files (x86)\python38-32\lib\site-packages\zmq\eventloop\zmqstream.py", line 127, in __init__
    self._init_io_state()
  File "c:\program files (x86)\python38-32\lib\site-packages\zmq\eventloop\zmqstream.py", line 546, in _init_io_state
    self.io_loop.add_handler(self.socket, self._handle_events, self.io_loop.READ)
  File "c:\program files (x86)\python38-32\lib\site-packages\tornado\platform\asyncio.py", line 100, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "c:\program files (x86)\python38-32\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
```
This was followed by:
```
2020-05-25 14:15:23,193 | CRITICAL | inkcut |
<html>
<h3>Sorry, an error prevented Inkcut from starting</h3>
<p>
This is either a bug or a required library may be missing on your system.
As always you can request help on the forums at
<a href="https://inkcut.org">https://inkcut.org</a>.
</p>

<p>
First try to restart the application. If the error persists you can try
clearing the saved settings in <a href="C:\Users\wyer/.config/inkcut">C:\Users\wyer/.config/inkcut</a>
and restart the application again</a>.
</p>

<p>
If that still doesn't work please report a new issue at
<a href="https://github.com/codelv/inkcut">https://github.com/codelv/inkcut</a>
with the following error:
</p>

<pre>self._event_puller = ZMQStream(pipe_in, self.io_loop)
  File "c:\program files (x86)\python38-32\lib\site-packages\zmq\eventloop\zmqstream.py", line 127, in __init__
    self._init_io_state()
  File "c:\program files (x86)\python38-32\lib\site-packages\zmq\eventloop\zmqstream.py", line 546, in _init_io_state
    self.io_loop.add_handler(self.socket, self._handle_events, self.io_loop.READ)
  File "c:\program files (x86)\python38-32\lib\site-packages\tornado\platform\asyncio.py", line 100, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "c:\program files (x86)\python38-32\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError</pre>

<p> and include the logs from <a href="C:\Users\wyer/.config/inkcut\logs">C:\Users\wyer/.config/inkcut\logs</a>.
</p>
</html>
```

**Comment by czernoch** [comment]
I have the same problem. Before this is resolved, [i found a solution](https://github.com/jupyter/notebook/issues/4613#issuecomment-491529024) in adding line after as existing:

```
import asyncio
```
per

```
import asyncio
asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
```




to the `asyncio.py` file in the python38 installation (line 30)
