### ISSUE TITLE
Crash on Arch linux, missing module enamlx

### ISSUE THREAD

**Issue by DanielMazurkiewicz** [inkcut/inkcut#291]
```
Logging to /home/daniel/.config/inkcut/logs/inkcut.txt
2020-11-15 11:21:33,296 | INFO    | inkcut | ========================================
2020-11-15 11:21:33,296 | INFO    | inkcut | Inkcut launched
2020-11-15 11:21:33,296 | INFO    | inkcut | Version: 2.1.0
2020-11-15 11:21:33,296 | INFO    | inkcut | Python: 3.8.6 (default, Sep 30 2020, 04:00:38)
[GCC 10.2.0]
2020-11-15 11:21:33,301 | INFO    | inkcut | System: uname_result(system='Linux', node='ideapad', release='5.9.8-arch1-1', version='#1 SMP PREEMPT Tue, 10 Nov 2020 22:44:11 +0000', machine='x86_64', processor='')
2020-11-15 11:21:33,301 | INFO    | inkcut | Executable: /usr/bin/python
2020-11-15 11:21:33,301 | INFO    | inkcut | Args: ['/usr/bin/inkcut']
2020-11-15 11:21:33,338 | INFO    | inkcut | Qt: 5.15.1 Api:
2020-11-15 11:21:33,338 | INFO    | inkcut | ========================================
2020-11-15 11:21:33,340 | ERROR   | inkcut | Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/inkcut/app.py", line 97, in main
    from inkcut.core.workbench import InkcutWorkbench
  File "/usr/lib/python3.8/site-packages/inkcut/core/workbench.py", line 15, in <module>
    import enamlx
ModuleNotFoundError: No module named 'enamlx'

Traceback (most recent call last):
  File "/usr/bin/inkcut", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/inkcut/app.py", line 97, in main
    from inkcut.core.workbench import InkcutWorkbench
  File "/usr/lib/python3.8/site-packages/inkcut/core/workbench.py", line 15, in <module>
    import enamlx
ModuleNotFoundError: No module named 'enamlx'
```

**Comment by frmdstryr** [comment]
Please try running `sudo python3 -m pip install enamlx`
