### ISSUE TITLE
Getting a weird Error when Trying to open (AttributeError: module 'inkex' has no attribute 'os')

### ISSUE THREAD

**Issue by Crono141** [inkcut/inkcut#331]
Just installed inkscape and inkcut to test interface and functionality.  Inkcut standalone runs just fine, but when I try to use either of the extension options within inkspace I get this error (for open)

> /home/crono141/.config/inkscape/extensions/inkcut_open.py:27: DeprecationWarning: inkex.localize was moved to inkex.localization.localize.
  inkex.localize()
/home/crono141/.config/inkscape/extensions/inkcut.py:28: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.spawn import find_executable
/home/crono141/.config/inkscape/extensions/inkcut_open.py:66: DeprecationWarning: Effect.affect is now `Effect.run()`. The `output` argument has changed.
  effect.affect()
/home/crono141/.config/inkscape/extensions/inkcut_open.py:53: DeprecationWarning: self.args[-1] is now self.options.input_file.
  document = convert_objects_to_paths(self.args[-1], self.document)
Traceback (most recent call last):
  File "/home/crono141/.config/inkscape/extensions/inkcut_open.py", line 66, in <module>
    effect.affect()
  File "/usr/share/inkscape/extensions/inkex/deprecated.py", line 183, in affect
    return self.run(args=args)
  File "/usr/share/inkscape/extensions/inkex/base.py", line 131, in run
    self.save_raw(self.effect())
  File "/home/crono141/.config/inkscape/extensions/inkcut_open.py", line 53, in effect
    document = convert_objects_to_paths(self.args[-1], self.document)
  File "/home/crono141/.config/inkscape/extensions/inkcut.py", line 38, in convert_objects_to_paths
    tempfile = inkex.os.path.splitext(file)[0] + "-prepare.svg"
AttributeError: module 'inkex' has no attribute 'os'

And this one for "cut selection":

> /home/crono141/.config/inkscape/extensions/inkcut_cut.py:27: DeprecationWarning: inkex.localize was moved to inkex.localization.localize.
  inkex.localize()
/home/crono141/.config/inkscape/extensions/inkcut.py:28: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.spawn import find_executable
/home/crono141/.config/inkscape/extensions/inkcut_cut.py:73: DeprecationWarning: Effect.affect is now `Effect.run()`. The `output` argument has changed.
  effect.affect()
/home/crono141/.config/inkscape/extensions/inkcut_cut.py:44: DeprecationWarning: Effect.selected is now a dict in the SvgDocumentElement class. Use `self.svg.selected`.
  nodes = self.selected
/home/crono141/.config/inkscape/extensions/inkcut_cut.py:50: DeprecationWarning: Effect.selected is now a dict in the SvgDocumentElement class. Use `self.svg.selected`.
  if contains_text(self.selected.values()):
/home/crono141/.config/inkscape/extensions/inkcut_cut.py:68: DeprecationWarning: inkex.etree was removed, use "from lxml import etree"
  p.stdin.write(inkex.etree.tostring(document))
/usr/lib/python3.10/subprocess.py:1067: ResourceWarning: subprocess 205113 is still running
  _warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback

Inkcut never opens in either case.  I do not have a cutter connected presently.  After poking around in inkscape extension manager, I find that inkcut_open.inx and inkut_cut.inx are both listed as orphan extensions.  Both of these files live alongside their corresponding .py files in the extensions folders under .config.

Prior to inkcut, I had installed inkscape-silhouette, but I removed all the offending files from that install before installing inkcut.

Running Manjaro and inkscape from pacman.

**Comment by raboof** [comment]
> File "/home/crono141/.config/inkscape/extensions/inkcut.py", line 38, in convert_objects_to_paths

Are you using the latest version of inkcut (2.1.3)? It looks like you might not be, since inkcut.py [should no longer exist in that location](https://github.com/inkcut/inkcut/commit/ddc1f9e63e7a769c71131b56f6a2a011c649635c)
