### ISSUE TITLE
Object reference deserializing doesn't work well with jsonpickle 2.2.0

### ISSUE THREAD

**Issue by karliss** [inkcut/inkcut#361]
This causes a lot of stuff in inkcut to break. Most obvious when copying devices, but there are other parts which cause multiple setting json parts to reference same object using "py/id" mechanism. 

Accidentally noticed this because one of my python environements had jsonpickle 2.2.0 and other had 2.1.0 With 2.1 everything is fine, but with it results half broken objects causing wide variety of errors depending on how inkcut uses them.

Not sure yet whether this is:
* jsonpickle py/id is completely broken in jsonpickle 2.2 in this case it wouldn't directly inkcut problem, although seems unlikely that an important feature like that would be completely broken (at least without very specific conditions)
* weird interaction between jsonpickle and Atom
* inkcut Model._getstate_ __setstate_overrides
* inkcut not passing the right flags for jsonpickle
* something else

**Easiest way to reproduce is:**
* Create a new device
* Copy device
* restart inkcut
* switch back and forth between copy and original device -> observe exception in console output

It is possible to observe some of the symptoms of having issues with reference deserialization without copying devices:
* delete all settings
* open inkcut and create a device
* restart inkcut observe that there is exception related to devicePlugin.device field. Current device points to one of the devices in list of all devices, so it makes sense that it gets serialized as reference.
```
2022-11-13 21:10:27,139 | WARNING | inkcut | Plugin inkcut.device failed to load state: Traceback (most recent call last):
  File "/home/karlis/pr_os/inkcut/inkcut/core/models.py", line 201, in _bind_observers
    self.__setstate__(state)
  File "/home/karlis/pr_os/inkcut_venv/lib/python3.10/site-packages/atom/atom.py", line 604, in __setstate__
    setattr(self, key, value)
TypeError: The 'device' member on the 'DevicePlugin' object must be of type '(Device)'. Got object of type 'atom.catom.atomlist' instead.
```

**Some other weirdness:**
When creating two devices based on same driver(the struct which defines size and supported protocols) and serializing with 2.2 the driver structure isn't shared, but copied device shares it. But when serializing with 2.1 it gets shared even when create 2 devices without copying (which is what I initially expected to happen).  Take this with grain of salt I might have seen it wrong.

Will update as I do further testing.

**Comment by karliss** [comment]
For now this is a smallest testcase I could make which fails with jsonpickle 2.2.0 but works with 2.1.0

```py
import pytest
import jsonpickle
#from atom.api import Instance, List, Int, Float, Atom
#from inkcut.core.api import Model
from inkcut.core.declarative import Declarative


class M1(Declarative):
    def aaa(self):
        pass


def test_foo():
    x = M1()
    y = M1()
    data = [x, y, y]

    ser = jsonpickle.encode(data)
    res = jsonpickle.decode(ser)
    print(res)
    assert res[1] == res[2]
```

**Comment by karliss** [comment]
After more debugging it seems that jsonpickle gets confused by attempting to serialized/deserialize "initialized" Event in enaml.core.declarative.Declarative .   Previous jsonpickle versions where able to somewhat deal with it, but with 2.2.0 the reference IDs goes wrong causing josonpickle to choose wrong objects in the wrong place of deserialized object structure.

The jsonpickle half of the problem can be also triggered by following code which doesn't use inkcut and enaml Declarative. First  commit where the problem starts is [d5ba0452c2b6534a669325a173fa1c4d4261b560](https://github.com/jsonpickle/jsonpickle/pull/383/commits/d5ba0452c2b6534a669325a173fa1c4d4261b560)

```py
class M3(Model):
    someev = Event().tag(config=True)
    def aaa(self):
        pass

def test_foo():
    x = M3()
    y = M3()
    data = [x, y, y]

    ser = jsonpickle.encode(data)
    res = jsonpickle.decode(ser)
    print(ser)
    print(res)
    assert res[1] == res[2]
```

Other half of problem is whether inkcut should even ask jsonpickle to attempt serializing this field. inkcut `Declarative` already has some code to exclude some but not all of the enaml `Declarative` fields from serialization.  Quick hack in  inkcut.Declarative.__getstate__ fixed the symptoms I observed, but I have no idea how this `initialized` field is used and whether not serializing it can cause other problems.
